spring:
  application:
    name: grandmas-food-delivery-api-integration-test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:grandmasfoodDB;MODE=MySQL
    username: shouldBeEnv
    password: shouldBeEnv
flyway:
  user: shouldBeEnv
  password: shouldBeEnv
  schemas: grandmasfoodDB
  url: jdbc:h2:file:mem/grandmasfoodDB
  locations: filesystem:db/migration